### ISSUE TITLE
iOS 9 compatability/readiness?

### ISSUE THREAD

**Issue by khappucino-nordstrom** [jeffh/JKVValue#2]
We're auditing our code for iOS 9. We expect JKVValue to be totally legit and seems to work so far. Is there anything we should be weary about for the new release?

**Comment by jeffh** [comment]
There shouldn't been any issues AFAIK. I haven't tried the newest beta that was released yesterday.

**Comment by jeffh** [comment]
I checked it. The only issue is with 'swizzleContainers' which I'll put a fix in the next couple days. But if you're not using that, everything else is good.

**Comment by khappucino-nordstrom** [comment]
sweet thanks jeff

**Comment by jeffh** [comment]
No problem! :)

Currently master has that fix. And if you prefer to use ios dynamic frameworks, master has that too. (I'll probably cut another version a few days from now).
