### ISSUE TITLE
Doesn't work (easily?) with Carthage

### ISSUE THREAD

**Issue by camelpunch** [jeffh/JKVValue#3]
Hi Jeff! Hope you're well.

I was recommended this library as a simpler alternative to [Mantle](https://github.com/Mantle/Mantle). However, I ran into great difficulty getting it working with Carthage. I'd manage to fiddle with it enough to get it working locally, but then it wouldn't [on Travis](https://travis-ci.org/camelpunch/RMQClient/builds/103168009) etc.

I'll provide some more details soon. Have you managed to include the project using Carthage?

Switching to Mantle as it has explicit support for now.

Cheers,

Andrew

**Comment by camelpunch** [comment]
Another thing: a `Cartfile.private` would probably mean I don't have to download your testing frameworks.

**Comment by jeffh** [comment]
Hey Andrew,

I haven't tested this via carthage. Carthage setup hasn't been the cleanest of things in the past few releases. I'll see if I can find some time to take a look at it.

**Comment by camelpunch** [comment]
Thanks. Let me know if I can help!

**Comment by jeffh** [comment]
I've fixed the carthage issues and pushed a new release (`v1.3.1`). Thanks for reporting the issue!
