### ISSUE TITLE
JKVValue Not compatible with watch os 2

### ISSUE THREAD

**Issue by lettierimarco** [jeffh/JKVValue#4]

**Comment by jeffh** [comment]
Thanks, I'll look into adding watchOS support when I get a chance. Otherwise a pull request is welcomed 😄

**Comment by jeffh** [comment]
Hey @lettierimarco, watch os target has been added on `master`, could you check it out and verify if it works for you use case?

Thanks,
Jeff

**Comment by lettierimarco** [comment]
It looks working, waiting for install via pod

**Comment by jeffh** [comment]
A new version has been cut! 🎊

- Jeff
